import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../app/globals.css";

import Sidebar from "@/app/components/Sidebar";
import ReduxProvider from "../store/ReduxProvider";
import { menus, otherMenus } from "../utils/menuLabels";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ReduxProvider>
          <div className="flex bg-white md:p-2">
            <Sidebar menus={menus} otherMenus={otherMenus} />
            <main className="flex-1 p-4">{children}</main>
            <Toaster />
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
